chore(EMI-1969) Collector signals schema
artsy/cohesion pull request #516
Opened 2024-07-29 20:24 UTC by erikdstock

The type of this PR is: **chore**

This PR resolves relates to [EMI-1969] and creates new properties for interactions with an artwork (page, screen or grid/collection item) that has collector signals visible on it. 

### Description

I used a mixin + `extends` to define and add the values from one place:
```ts
export interface CollectorSignalsValues {
  signal_labels?: CollectorSignalLabel[]
  signal_lot_watcher_count?: number
  signal_bid_count?: number
}
```
Added to:

- [ ] ClickedMainArtworkGrid
- [ ] ClickedArtworkGroup
- [ ] ClickedAuctionGroup
- [ ] ClickedBuyNow
- [ ] ClickedBid (Migrated from usage in DeprecatedSchema - will need to be updated in artsy/force)
- [ ] ClickedContactGallery (Migrated from usage in DeprecatedSchema - will need to be updated in artsy/force)
- Tap events
- [ ] TappedMainArtworkGrid
- [ ] TappedArtworkGroup
- [ ] TappedAuctionGroup
- [ ] TappedBid
- [ ] TappedBuyNow
- [ ] TappedContactGallery

- [x] If I've added a new file to the tree I've exported it from the common [`index.ts`](https://github.com/artsy/cohesion/blob/main/src/Schema/Events/index.ts)
- [x] I've added comments with examples for any new interfaces and ensured that they're in the docs
- [x] No platform-specific terminology has been used outside of `click` and `tap` (platform is inferred by the DB storing events)

2024-07-29 20:53 UTC, damassi commented on src/Schema/Events/Click.ts
> +    CollectorSignalsValues {
No cleverness in this codebase! Don't want to extend or anything like that, especially in regards to mixing types. Keep this as boring as possible 🙏

2024-07-29 20:53 UTC, damassi commented on src/Schema/Events/Click.ts
> +    CollectorSignalsValues {
Ditto here and elsewhere. We can surely achieve the same ends without crossing wires.

2024-07-29 20:54 UTC, damassi requested changes
Happy to pair on these change requests! We shouldn't be extending the tracking schema in this way.

2024-07-29 21:10 UTC, damassi approved these changes
Thanks for the updates 👍

2024-07-30 19:53 UTC, merged

2024-07-30 19:55 UTC, artsyit commented
<!-- GITHUB_RELEASE COMMENT: released -->
:rocket: PR was released in [`v4.196.0`](https://github.com/artsy/cohesion/releases/tag/v4.196.0) :rocket: